#https://github.com/alexta69/metube
---
version: '2.0'
services:
  metube:
    image: 'alexta69/metube:latest'
    expose:
      - port: 8081
        as: 80
        to:
          - global: true
profiles:
  compute:
    metube:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        metube:
          denom: uakt
          amount: 10000
deployment:
  metube:
    dcloud:
      profile: metube
      count: 1
