#https://github.com/szabodanika/microbin/
---
version: '2.0'
services:
  microbin:
    image: 'danielszabo99/microbin:latest'
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - MICROBIN_PORT=8080
      - MICROBIN_PRIVATE=true
      - MICROBIN_HIDE_LOGO=true
      - MICROBIN_HIGHLIGHTSYNTAX=true
      - 'MICROBIN_PUBLIC_PATH=https://bin.netadao.zone'
      - MICROBIN_QR=true
      - MICROBIN_TITLE=Neta DAO MicroBin
profiles:
  compute:
    microbin:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        microbin:
          denom: uakt
          amount: 1000
deployment:
  microbin:
    dcloud:
      profile: microbin
      count: 1
