#https://github.com/zyachel/quetre
---
version: '2.0'
services:
  quetre:
    image: 'quay.io/pussthecatorg/quetre:latest'
    expose:
      - port: 3000
        as: 80
        accept:
          - quetre.site.tld
        to:
          - global: true
    env:
      - NODE_ENV=production
      - PORT=3000
profiles:
  compute:
    quetre:
      resources:
        cpu:
          units: 0.4
        memory:
          size: 256Mi
        storage:
          - size: 256Mi
  placement:
    dcloud:
      pricing:
        quetre:
          denom: uakt
          amount: 10000
deployment:
  quetre:
    dcloud:
      profile: quetre
      count: 1
