#https://github.com/RobinLinus/snapdrop
---
version: '2.0'
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    snapdrop:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        snapdrop:
          denom: uakt
          amount: 10000
deployment:
  snapdrop:
    dcloud:
      profile: snapdrop
      count: 1
