#https://github.com/syncthing/syncthing
---
version: '2.0'
services:
  syncthing:
    image: 'syncthing/syncthing:latest'
    expose:
      - port: 8384
        as: 80
        to:
          - global: true
      - port: 22000
        as: 22000
        proto: tcp
        to:
          - global: true
profiles:
  compute:
    syncthing:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    dcloud:
      pricing:
        syncthing:
          denom: uakt
          amount: 10000
deployment:
  syncthing:
    dcloud:
      profile: syncthing
      count: 1
